# Generated by Django 3.1.5 on 2021-01-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210110_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='nyt_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
