# Generated by Django 3.1.5 on 2021-01-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_topic_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='colour',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
