# Generated by Django 3.1.5 on 2021-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
