# Generated by Django 3.1.5 on 2021-01-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '__first__'),
        ('podcasts', '0002_auto_20210109_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='news.Topic'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
